# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JpP9Uow9ODA0sk9G-o6oVpWyOTt5rQSn
"""

import pandas as pd
from google.colab import files
up=files.upload()

import pandas as pd
X=pd.read_csv("mm.csv")
X.head()#displays first 5 column of data
X.tail()#displays last 5 columns of data
X.shape
X.info()

X.isnull()

#count number of nulls in each column:
X.isnull().sum()

#we can drop all rows with a null using X.dropna() but this is not at all intelligence as a lot of data will be gone
#we can also delete columns with null using X.dropna(aXis=1)
#other way out is IMPUTAION-add mean median or mode at emplty places

ch1=X['Number Dead']#eXtract the column where changes have to be made
#we are chosing a Series
ch1.shape
#ch1 is a Seires, info() is not associated with series
ch1.head()

ch1_m=ch1.mean()#calculated mean of Number Dead
ch1_m

#now fill this mean on places where there is no value in that column and make changes in original file using inplace
ch1_m=ch1.fillna('ch1_m',inplace=True)



X.isnull().sum()#number dead null=0 now

X['Migration Route'].describe()

X['Migration Route'].value_counts().describe()

X.corr()

'''Positive numbers indicate a positive correlation — one goes up the other goes up — 
and negative numbers represent an inverse correlation — one goes up the other goes down.
 1.0 indicates a perfect correlation'''

#we saw that number dead is a series and not a data frame but it can be treated ad a data frame by using double brackets
type(X[['Number Dead']])

#now we can add one more column to it
sub=X[['Number Dead','Number of Children']]
sub.head()

import matplotlib.pyplot as plt
X.head()
X.plot(x='Total Dead and Missing',y='Number of Males',kind='scatter')

import numpy as np
fig, axes = plt.subplots(nrows=2, ncols=2)
ax0, ax1, ax2, ax3 = axes.flatten()
n_bins=10
ax3.hist(X['Number of Children'], n_bins, histtype='bar')
ax3.set_title('different sample sizes')

fig.tight_layout()
plt.show()

